## Assignment 3

In [4]:
# Q1

def div(a,b):
    try:
        c=a/b
    except ZeroDivisionError:
        print("Denominator can't be zero")
    else:
        print(c)
div(5,0)

Denominator can't be zero


In [10]:
#Q2

subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"] 

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i+' '+j+' '+ k)


Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [14]:
#Task2

#Q1

import numpy as np

def generateMatrix(element,column):
    return np.column_stack([element**(column-1-i) for i in range(column)])

print(generateMatrix(np.array([1, 2, 3, 4,5]),4))

#Using Vander method
def generateMatrix(element,column):
    return np.vander(element,column)

print("\n Using Vander Method : \n")
print(generateMatrix(np.array([1, 2, 3, 4,5]),4))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

 Using Vander Method : 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
